#!/usr/bin/env bash

rabbitmq_config_OnlyEnableThesePlugins() {
  echo "$RABBITMQ_ONLY_ENABLE_THESE_PLUGINS" | sort
}
rabbitmq_vhosts() {
  rabbitmqctl list_vhosts | tail -n +2 | tr '\n' ' '
}
rabbitmq_plugins_installed_list() {
  rabbitmq-plugins list -m | sort
}

rabbitmq_plugins_all_enabled_list() {
  rabbitmq-plugins list -E -e -m | sort
}

rabbitmq_plugins_explicitly_enabled_list() {
  rabbitmq-plugins list -E -m | sort
}
