#!/usr/bin/env bash

TEST="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# shellcheck disable=SC1090
source $TEST/store_helpers

RABBITMQ_EXPORT_FILE="/tmp/rabbitmq-diagnostic-report.${TEST_RUN_ID:?must be defined}.json"

rabbitmq_config_OnlyEnableThesePlugins() {
  echo "$RABBITMQ_ONLY_ENABLE_THESE_PLUGINS" | sort
}
rabbitmq_export() {
  [ -r $RABBITMQ_EXPORT_FILE ] || rabbitmq-admin export $RABBITMQ_EXPORT_FILE  1>&2
}
rabbitmq_vhosts() {
  rabbitmq_export && extract_vhosts $RABBITMQ_EXPORT_FILE
}
rabbitmq_users() {
  rabbitmq_export && extract_users $RABBITMQ_EXPORT_FILE
}
rabbitmq_permissions() {
  rabbitmq_export && extract_permissions $RABBITMQ_EXPORT_FILE
}
rabbitmq_topic_permissions() {
  rabbitmq_export && extract_topic_permissions $RABBITMQ_EXPORT_FILE
}
rabbitmq_policies() {
  rabbitmq_export && extract_policies $RABBITMQ_EXPORT_FILE
}
rabbitmq_plugins_all_enabled_list() {
  rabbitmq-plugins list -E -e -m | sort
}
rabbitmq_plugins_explicitly_enabled_list() {
  rabbitmq-plugins list -E -m | sort
}
rabbitmq_plugins_installed_list() {
  rabbitmq-plugins list -m | sort
}
rabbitmq_parameters() {
  rabbitmq_export && extract_parameters $RABBITMQ_EXPORT_FILE
}
rabbitmq_global_parameters() {
  rabbitmq_export && extract_global_parameters $RABBITMQ_EXPORT_FILE
}
