#!/usr/bin/env bash

rabbitmq_config_OnlyEnableThesePlugins() {
  echo "$RABBITMQ_ONLY_ENABLE_THESE_PLUGINS" | sort
}
rabbitmq_vhosts() {
  rabbitmqctl list_vhosts | tail -n +2 | tr '\n' ' '
}
rabbitmq_vhost_limits() {
  local vhost
  vhost=$1
  rabbitmqctl list_vhost_limits -p $vhost | tail -n +2 | sort
}
rabbitmq_users() {
  rabbitmqctl list_users | tail -n +2 | sort
}
rabbitmq_permissions() {
  local vhost
  vhost=$1
  rabbitmqctl list_permissions -p $vhost | tail -n +2 | sort
}
rabbitmq_topic_permissions() {
  local vhost
  vhost=$1
  rabbitmqctl list_topic_permissions -p $vhost | tail -n +2 | sort
}
rabbitmq_policies() {
  local vhost
  vhost=$1
  rabbitmqctl list_policies -p $vhost | tail -n +2 | sort
}
rabbitmq_operator_policies() {
  local vhost
  vhost=$1
  rabbitmqctl list_operator_policies -p $vhost | tail -n +2 | sort
}
rabbitmq_plugins_installed_list() {
  rabbitmq-plugins list -m | sort
}
rabbitmq_plugins_all_enabled_list() {
  rabbitmq-plugins list -E -e -m | sort
}
rabbitmq_plugins_explicitly_enabled_list() {
  rabbitmq-plugins list -E -m | sort
}
rabbitmq_parameters() {
  local vhost
  vhost=$1
  rabbitmqctl list_parameters -p $vhost | tail -n +2 | sort
}
rabbitmq_global_parameters() {
  rabbitmqctl list_global_parameters | tail -n +2 | sort
}
# Introduced in 3.7.0
is_topic_permissions_supported() {
  [[ -n "$(rabbitmqctl 2>&1 | grep list_topic_permissions)" ]]
}
