#!/usr/bin/env bash

store_exists() {
  [[ -f $DIAGNOSTICS_SNAPSHOT ]]
}
extract_vhosts() {
  jq -r .vhosts[].name $1 | sort
}
store_vhosts() {
  store_exists && extract_vhosts $DIAGNOSTICS_SNAPSHOT
}
extract_users() {
 jq -c -r '.users[] | [.name,.tags]' $1 | sort
}
store_users() {
  store_exists && extract_users $DIAGNOSTICS_SNAPSHOT
}
extract_permissions() {
  jq -c -r '.permissions[] | [.vhost,.user,.configure,.write,.read] ' $1 | sort
}
store_permissions() {
  store_exists && extract_permissions $DIAGNOSTICS_SNAPSHOT
}
extract_topic_permissions() {
  jq -c -r '.topic_permissions[] | [.vhost,.user,.exchange,.write,.read] ' $1 | sort
}
store_topic_permissions() {
  store_exists && extract_topic_permissions $DIAGNOSTICS_SNAPSHOT
}
extract_policies() {
  jq -c -r '.policies[] | [.vhost,.name,.pattern,.priority,.definition] ' $1 | sort
}
store_policies() {
  store_exists && extract_policies $DIAGNOSTICS_SNAPSHOT
}
extract_parameters() {
  jq -c '.parameters[] | [.vhost,.name,.component,.value]' $1 | sort
}
store_parameters() {
  store_exists && extract_parameters $DIAGNOSTICS_SNAPSHOT
}
extract_global_parameters() {
  jq -c -r '.global_parameters[] | [.name,.value]' $1 | sort
}
store_global_parameters() {
  store_exists && extract_global_parameters $DIAGNOSTICS_SNAPSHOT
}
