#!/usr/bin/env bash

store_vhosts_exists() {
  [[ -f $DIAGNOSTICS_VHOSTS_SNAPSHOT ]]
}
store_vhosts() {
  local vhosts_file
  vhosts_file=$DIAGNOSTICS_VHOSTS_SNAPSHOT

  [ -r $vhosts_file ] && (cat $vhosts_file | tr '\n' ' ')
}
store_vhost_limits() {
  local vhost limits_file
  if [[ "$1" == '/' ]]
  then
    vhost='default'
  else
    vhost=$1
  fi
  limits_file="${DIAGNOSTICS_STORE_DIR}/${vhost}_limits.snapshot"

  [ -r $limits_file ] && cat $limits_file
}
store_users_exists() {
  [[ -f $DIAGNOSTICS_USERS_SNAPSHOT ]]
}
store_permissions() {
  local vhost permissions_file
  if [[ "$1" == '/' ]]
  then
    vhost='default'
  else
    vhost=$1
  fi
  permissions_file="${DIAGNOSTICS_STORE_DIR}/${vhost}_permissions.snapshot"

  [ -r $permissions_file ] && cat $permissions_file
}
store_topic_permissions() {
  local vhost topic_permissions_file
  if [[ "$1" == '/' ]]
  then
    vhost='default'
  else
    vhost=$1
  fi
  topic_permissions_file="${DIAGNOSTICS_STORE_DIR}/${vhost}_topic_permissions.snapshot"

  [ -r $topic_permissions_file ] && cat $topic_permissions_file
}
store_policies() {
  local vhost policies_file
  if [[ "$1" == '/' ]]
  then
    vhost='default'
  else
    vhost=$1
  fi
  policies_file="${DIAGNOSTICS_STORE_DIR}/${vhost}_policies.snapshot"

  [ -r $policies_file ] && cat $policies_file
}
store_operator_policies() {
  local vhost policies_file
  if [[ "$1" == '/' ]]
  then
    vhost='default'
  else
    vhost=$1
  fi

  policies_file="${DIAGNOSTICS_STORE_DIR}/${vhost}_operator_policies.snapshot"
  [ -r $policies_file ] && cat $policies_file
}
store_parameters() {
  local vhost parameters_file
  if [[ "$1" == '/' ]]
  then
    vhost='default'
  else
    vhost=$1
  fi

  parameters_file="${DIAGNOSTICS_STORE_DIR}/${vhost}_parameters.snapshot"
  [ -r $parameters_file ] && cat $parameters_file
}
