#!/usr/bin/env bash

store_vhosts_exists() {
  [[ -f $DIAGNOSTICS_VHOSTS_SNAPSHOT ]]
}
store_vhosts() {
  local vhosts_file
  vhosts_file=$DIAGNOSTICS_VHOSTS_SNAPSHOT

  [ -r $vhosts_file ] && (cat $vhosts_file | tr '\n' ' ')
}
store_users_exists() {
  [[ -f $DIAGNOSTICS_USERS_SNAPSHOT ]]
}
store_permissions() {
  local vhost permissions_file
  if [[ "$1" == '/' ]]
  then
    vhost='default'
  else
    vhost=$1
  fi
  permissions_file="${DIAGNOSTICS_STORE_DIR}/${vhost}_permissions.snapshot"

  [ -r $permissions_file ] && cat $permissions_file
}
