#!/usr/bin/env bash

[[ $DEBUG = true ]] && set -x

SCRIPT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../script" && pwd )"
TEST="$( cd "$( dirname "${BASH_SOURCE[0]}" )/test" && pwd )"

main() {
  resolve_dependencies

  load_deployment_info

  if [[ "$*" =~ ^w ]]
  then
    autotest
  else
    test_all
  fi
}

load_deployment_info() {
  echo "Loading ${BOSH_DEPLOYMENT:?must be defined} deployment info ..."
  # shellcheck source=../script/_load_deployment_info
  source $SCRIPT/_load_deployment_info && ${SCRIPT}/_print_deployment_info
}

resolve_dependencies() {
  [[ "$(brew list)" =~ fsw ]] || brew install fsw

  go get github.com/progrium/basht
}

autotest() {
  local file

  fsw --latency 0.2 -i '.bash' -e '.' $TEST | while read -r file
  do
    is_test_file? "$file" || file="$TEST/$(basename -s '.bash' "$file")_test.bash"
    test_one "$file" && date
  done
}

is_test_file?() {
  local file
  file="$1"

  [[ "$file" =~ _test.bash$ ]]
}

test_all() {
  basht $TEST/*_test.bash
}

test_one() {
  local file
  file="$1"

  [ -f "$file" ] && basht "$file"
}

main "$@"
