#!/usr/bin/env bash

SCRIPT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

DEPLOYMENT_CONFIGURATION="${DEPLOYMENT_CONFIGURATION:?must be defined}"
BOSH_DEPLOYMENT="${BOSH_DEPLOYMENT:?must be defined}"
RMQ_BOSH_RELEASE_MANIFEST="${RMQ_BOSH_RELEASE_MANIFEST:?must be defined}"

bosh upload-release "$RMQ_BOSH_RELEASE_MANIFEST"

declare -a BOSH_OPERATIONS

if [[ "$(yaml2json < "$DEPLOYMENT_CONFIGURATION" | jq -r '.cf_apps_domain')" != null ]]
then
  BOSH_OPERATIONS+=("--ops-file=$SCRIPT/../operations/register-routes.yml")
fi

# We always want netdata running on our RabbitMQ node hosts
BOSH_OPERATIONS+=("--ops-file=$SCRIPT/../operations/add-netdata.yml")
# We always want perf + friends running on our RabbitMQ node hosts
BOSH_OPERATIONS+=("--ops-file=$SCRIPT/../operations/add-apt.yml")
BOSH_OPERATIONS+=("--ops-file=$SCRIPT/../operations/add-rabtap.yml")

if [[ "$(yaml2json < "$DEPLOYMENT_CONFIGURATION" | jq -r '.rmq_deploy_benchmark_tool')" == "true" ]]
then
  BOSH_OPERATIONS+=("--ops-file=$SCRIPT/../operations/deploy-perftest.yml")
fi

VARS_FILE="$SCRIPT/../deployment_configurations/$BOSH_DEPLOYMENT.yml"

bosh --deployment="$BOSH_DEPLOYMENT" deploy --no-redact \
  "${BOSH_OPERATIONS[@]}" \
  --vars-file="${VARS_FILE:?must be defined}" \
  rabbitmq-server-deployment-template.yml "$@"

# shellcheck source=script/_load_deployment_info
. "$SCRIPT"/_load_deployment_info
# shellcheck source=script/_print_deployment_info
. "$SCRIPT"/_print_deployment_info
