#!/usr/bin/env bash

SCRIPT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

DEPLOYMENT_CONFIGURATION="${DEPLOYMENT_CONFIGURATION:?must be defined}"
BOSH_DEPLOYMENT="${BOSH_DEPLOYMENT:?must be defined}"
RMQ_BOSH_RELEASE_MANIFEST="${RMQ_BOSH_RELEASE_MANIFEST:?must be defined}"

bosh upload-release "$RMQ_BOSH_RELEASE_MANIFEST"

declare -a BOSH_OPERATIONS
if [[ "$(yq -r '.datadog_api_key' < "$DEPLOYMENT_CONFIGURATION")" != null ]]
then
  BOSH_OPERATIONS+=("--ops-file=$SCRIPT/../operations/add-datadog-agent.yml")
fi

if [[ "$(yq -r '.cf_apps_domain' < "$DEPLOYMENT_CONFIGURATION")" != null ]]
then
  BOSH_OPERATIONS+=("--ops-file=$SCRIPT/../operations/register-routes.yml")
fi

BOSH_OPERATIONS+=("--ops-file=$SCRIPT/../operations/add-tmux.yml")
BOSH_OPERATIONS+=("--ops-file=$SCRIPT/../operations/add-netdata.yml")

bosh --deployment="$BOSH_DEPLOYMENT" deploy --no-redact \
  "${BOSH_OPERATIONS[@]}" \
  --vars-file="$SCRIPT/../deployment_configurations/$BOSH_DEPLOYMENT.yml" \
  rabbitmq-server-deployment-template.yml "$@"

RMQ_NODE_IPS=$(bosh -d $BOSH_DEPLOYMENT vms --column=IPs --json | jq -r '."Tables"[0]."Rows" | map(."ips") | join(", ")')
RMQ_CUPS=$(bosh -d $BOSH_DEPLOYMENT vms --column=IPs --json | jq --arg USER $RMQ_SERVER_ADMIN_USER --arg PASS "$RMQ_SERVER_ADMIN_PASS" -rc '."Tables"[0]."Rows" | {"urls": map("amqp://" + $USER + ":" + $PASS + "@" + ."ips" + ":5672")}')
