#!/usr/bin/env bash

SCRIPT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

set -o pipefail

find "$SCRIPT"/../dev_releases/rabbitmq-server -type f -name 'rabbitmq-server-*.yml' |
  sort --reverse --version-sort |
  while read -r rmq_bosh_release
  do
    rmq_bosh_release_no_ext="${rmq_bosh_release%.yml}"
    echo "${rmq_bosh_release_no_ext##*/rabbitmq-server-}"
  done
