#!/usr/bin/env bash

SCRIPT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

set -o pipefail

find "$SCRIPT"/../releases/rabbitmq-server -name 'rabbitmq-server-*.yml' |
sort -rV |
while read -r local_final_release_path
do
  local_final_release_file="${local_final_release_path##*/}"
  local_final_release_name="${local_final_release_file%.yml}"
  local_final_release_version="${local_final_release_name#rabbitmq-server-}"
  echo "$local_final_release_version"
done
