#!/usr/bin/env bash

separator() {
  printf "%0.1s%0.1s%0.1s%0.1s%0.1s" "+" "-"{1..24} "+" "-"{1..86} "+"
  echo
}

row() {
  printf "| %-22s | %-84s |\\n" "$1" "$2"
}

separator
[ -z "$RMQ_MANAGEMENT_URL" ] || row "RMQ MANAGEMENT URL" "$RMQ_MANAGEMENT_URL"

separator
for rmq_amqp_url in $RMQ_AMQP_URLS
do
  row "RMQ AMQP URL" "$rmq_amqp_url"
done

separator
for rmq_netdata_url in $RMQ_NETDATA_URLS
do
  row "RMQ NETDATA URL" "$rmq_netdata_url"
done

separator
row "RMQ VERSION" "$RMQ_VERSION"
row "ERLANG VERSION" "$ERLANG_VERSION"

separator
row "RMQ VM" "$RMQ_VM_TYPE"
row "RMQ VM PERSISTENT DISK" "$RMQ_PERSISTENT_DISK_TYPE"

separator
row "BOSH DEPLOYMENT" "$BOSH_DEPLOYMENT"
row "BOSH RELEASE VERSION" "$RMQ_BOSH_RELEASE_VERSION"

separator
