#!/usr/bin/env bash

[ -n "$SCRIPT" ] || SCRIPT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "
Availability zone to deploy RabbitMQ in:"
select RMQ_AZ in $("$SCRIPT"/_azs)
do
  export RMQ_AZ
  break
done
