#!/usr/bin/env bash

[ -n "$SCRIPT" ] || SCRIPT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

RMQ_SERVER_ADMIN_USER="admin"
RMQ_SERVER_ADMIN_PASS="$("$SCRIPT"/_random_secret)"

export RMQ_SERVER_ADMIN_USER RMQ_SERVER_ADMIN_PASS
