#!/usr/bin/env bash

set -e

main() {
  delete_dev_releases_locally
  delete_dev_releases_from_bosh
}

function delete_dev_releases_locally() {
  rm -fr dev_releases
}
function delete_dev_releases_from_bosh() {
  for version in $(dev_releases)
  do
    bosh delete-release -n rabbitmq-server/$version 
  done
}
function dev_releases() {
  bosh releases | awk '{print $2}' | grep '.*dev.*[0-9]$'
}

main
