#!/usr/bin/env bash

set -e

main() {
  delete_dev_releases_locally
  delete_dev_releases_from_bosh
}

delete_dev_releases_locally() {
  rm -fr dev_releases
}

delete_dev_releases_from_bosh() {
  for dev_release_version in $(dev_releases_versions)
  do
    bosh delete-release -n rabbitmq-server/"$dev_release_version"
  done
}

dev_releases_versions() {
  bosh releases |
    awk '/rabbitmq-server.*\+dev\.[0-9]+ / { print $2 }'
}

main
