#!/usr/bin/env bash

set -e

[ -z "$DEBUG" ] || set -x

LASTPASS_BOSH_DIRECTOR_CREDENTIALS="Shared-London Services/london-ci/bosh-env-tarantino"

BOSH_DIRECTOR_FQDN="tarantino.directors.cf-app.com"

RMQ_PACKAGE="https://github.com/rabbitmq/rabbitmq-server/releases/download/rabbitmq_v3_6_9/rabbitmq-server-generic-unix-3.6.9.tar.xz"
NODES_COUNT=1
DEPLOYMENT_NAME="rmq-$USER"
SERVER_USER="admin"
SERVER_PASS="InsecureDefaultPassword"
ERLANG_COOKIE="InsecureDefaultCookie"


deployment_exists() {
  [ -f deployment ]
}

ensure_logged_in() {
  bosh stemcells &>/dev/null ||
  bosh login "$(bosh_username)" "$(bosh_password)"
}

bosh_username() {
  lpass show --username "$LASTPASS_BOSH_DIRECTOR_CREDENTIALS"
}

bosh_password() {
  lpass show --password "$LASTPASS_BOSH_DIRECTOR_CREDENTIALS"
}


main() {
  ensure_logged_in
  create_deployment
}

create_deployment() {
  if deployment_exists
  then
    while true; do
      read -p "Deployment already exists, do you want to overwrite it [yn]? " yn
      case $yn in
        [Yy]* ) prompt_and_generate_vars
                break;;
        [Nn]* ) exit;;
        * ) echo "Please answer y or n.";;
      esac
    done
  else
    echo "It looks like this is your first deploy"
    prompt_and_generate_vars
  fi
}

prompt_and_generate_vars() {
  echo
  read -rp "What name would you like to give your deployment? (press enter for $DEPLOYMENT_NAME): " deployment_name
  DEPLOYMENT_NAME="${deployment_name:=$DEPLOYMENT_NAME}"

  echo
  read -rp "Which RabbitMQ package do you want to deploy? (press enter for $RMQ_PACKAGE): " rmq_package
  RMQ_PACKAGE="${rmq_package:=$RMQ_PACKAGE}"

  echo
  read -rp "What username should we set for the Management UI? (press enter for $SERVER_USER): " server_user
  SERVER_USER="${server_user:=$SERVER_USER}"

  echo
  read -rp "What password should we set for the Management UI? (press enter for $SERVER_PASS): " server_pass
  SERVER_PASS="${server_pass:=$SERVER_PASS}"

  echo
  read -rp "What Erlang cookie should we set? (press enter for $ERLANG_COOKIE): " erlang_cookie
  ERLANG_COOKIE="${erlang_cookie:=$ERLANG_COOKIE}"

  echo
  read -rp "Lastly, how many nodes should there be in this cluster? (press enter for $NODES_COUNT): " nodes_count
  NODES_COUNT="${nodes_count:=$NODES_COUNT}"

  cat > deployment <<EOF
RMQ_PACKAGE=$RMQ_PACKAGE

DEPLOYMENT_NAME=$DEPLOYMENT_NAME
BOSH_DIRECTOR_FQDN=$BOSH_DIRECTOR_FQDN

SERVER_USER=$SERVER_USER
SERVER_PASS=$SERVER_PASS

ERLANG_COOKIE=$ERLANG_COOKIE
NODES_COUNT=$NODES_COUNT
EOF

  echo "
  New deploymnt file created

  You can now deploy with script/deploy
"
}

main
