#!/usr/bin/env bash

set -e

[ -z "$DEBUG" ] || set -x

RMQ_PACKAGE="https://github.com/rabbitmq/rabbitmq-server/releases/download/rabbitmq_v3_6_9/rabbitmq-server-generic-unix-3.6.9.tar.xz"
NODES_COUNT=2
DEPLOYMENT_NAME="rmq-$USER"
SERVER_USER="admin"
SERVER_PASS="InsecureDefaultPassword"
ERLANG_COOKIE="InsecureDefaultCookie"
BOSH_DIRECTOR_FQDN="tarantino.directors.cf-app.com"

main() {
  if should_create_new_manifest
  then
    generate_deployment
    generate_manifest
  fi
  ok
}

should_create_new_manifest() {
  if manifest_exists
  then
    read -rp "Do you want to overwrite the existing manifest? [yn] " overwrite
    [[ "$overwrite" =~ [Yy] ]]
  else
    true
  fi
}

manifest_exists() {
  [ -f deployment ] && [ -f manifest.yml ]
}

generate_deployment() {
  echo
  read -rp "What name would you like to give your deployment? (press enter for $DEPLOYMENT_NAME): " deployment_name
  DEPLOYMENT_NAME="${deployment_name:=$DEPLOYMENT_NAME}"

  echo
  read -rp "Which RabbitMQ package do you want to deploy? (press enter for $RMQ_PACKAGE): " rmq_package
  RMQ_PACKAGE="${rmq_package:=$RMQ_PACKAGE}"

  echo
  read -rp "What username should we set for the Management UI? (press enter for $SERVER_USER): " server_user
  SERVER_USER="${server_user:=$SERVER_USER}"

  echo
  read -rp "What password should we set for the Management UI? (press enter for $SERVER_PASS): " server_pass
  SERVER_PASS="${server_pass:=$SERVER_PASS}"

  echo
  read -rp "What Erlang cookie should we set? (press enter for $ERLANG_COOKIE): " erlang_cookie
  ERLANG_COOKIE="${erlang_cookie:=$ERLANG_COOKIE}"

  echo
  read -rp "Lastly, how many nodes should there be in this cluster? (press enter for $NODES_COUNT): " nodes_count
  NODES_COUNT="${nodes_count:=$NODES_COUNT}"

  cat > deployment <<EOF
RMQ_PACKAGE=$RMQ_PACKAGE

DEPLOYMENT_NAME=$DEPLOYMENT_NAME
BOSH_DIRECTOR_FQDN=$BOSH_DIRECTOR_FQDN

SERVER_USER=$SERVER_USER
SERVER_PASS=$SERVER_PASS

ERLANG_COOKIE=$ERLANG_COOKIE
NODES_COUNT=$NODES_COUNT
EOF
}

generate_manifest() {
  . deployment
  cat - rabbitmq-server.yml > manifest.yml <<EOF
rabbitmq_generic_unix: &rabbitmq_generic_unix $RMQ_PACKAGE
deployment_name: &deployment_name $DEPLOYMENT_NAME

server_host: &server_host $DEPLOYMENT_NAME.$BOSH_DIRECTOR_FQDN
server_user: &server_user $SERVER_USER
server_pass: &server_pass $SERVER_PASS

erlang_cookie: &erlang_cookie $ERLANG_COOKIE

server_count: &server_count $NODES_COUNT
EOF
}

ok() {
  echo "Manifest created, you can now deploy with script/deploy"
}

main
