#!/usr/bin/env bash

PRIVATE_CONFIG_CREDENTIALS="Shared-RabbitMQ/rabbitmq-server-boshrelease/config/private.yml"

set -e

if [ -z "$1" ]
then
  echo "First argument must be the release version"
  echo "Release versions that already exist:"
  cd releases/rabbitmq-server/
  ls rabbitmq-server-*.yml
  exit 1
fi

main() {
  lpass_login
  ensure_private_config_exists
  bosh create-release --with-tarball --final --version "$@"
}

lpass_login() {
  [[ $(lpass status) =~ Logged\ in\ as.*@pivotal.io ]] || (
    echo "You must   lpass login   with your pivotal.io user"
    exit 1
  )
}

ensure_private_config_exists() {
  if [ ! -e config/private.yml ]
  then
    echo "You are missing credentials required to upload blobs
Copying config/private.yml from LastPass..."
    lpass show --note "$PRIVATE_CONFIG_CREDENTIALS" > config/private.yml
  fi
}


main "$@"
