#!/usr/bin/env bash

set -e

[ -z "$DEBUG" ] || set -x

LASTPASS_BOSH_DIRECTOR_CREDENTIALS="Shared-London Services/london-ci/bosh-env-tarantino"

main() {
  lpass_login
  ensure_logged_in
  delete_deployment
  delete_manifest
}

lpass_login() {
  [[ $(lpass status) =~ Logged\ in\ as.*@pivotal.io ]] || (
    echo "You must   lpass login   with your pivotal.io user"
    exit 1
  )
}

ensure_logged_in() {
  bosh stemcells &>/dev/null || (
    bosh -n target "$(bosh_target)"
    bosh login "$(bosh_username)" "$(bosh_password)"
  )
}

bosh_target() {
  lpass show --notes "$LASTPASS_BOSH_DIRECTOR_CREDENTIALS" |
    awk '/bosh-target/ { print $2 }'
}

bosh_username() {
  lpass show --username "$LASTPASS_BOSH_DIRECTOR_CREDENTIALS"
}

bosh_password() {
  lpass show --password "$LASTPASS_BOSH_DIRECTOR_CREDENTIALS"
}

manifest_exists() {
  [ -f deployment ] && [ -f manifest.yml ]
}

delete_deployment() {
  if manifest_exists
  then
    # shellcheck source=/dev/null
    . deployment
    bosh delete deployment "$DEPLOYMENT_NAME" --force
  else
    echo "It doesn't seem that you have created a manifest, you may want to first run script/create-manifest"
  fi
}

delete_manifest() {
  local delete

  read -rp "Do you want to delete the manifest? (y|n) " delete
  [[ ! "$delete" =~ ^[Yy] ]] || rm -f deployment manifest.yml
}

main
