#!/usr/bin/env bash

set -e

[ -z "$DEBUG" ] || set -x

LASTPASS_BOSH_DIRECTOR_CREDENTIALS="Shared-London Services/london-ci/bosh-env-tarantino"

main() {
  ensure_logged_in
  delete_deployment
  delete_manifest
}

ensure_logged_in() {
  bosh stemcells &>/dev/null ||
    bosh login "$(bosh_username)" "$(bosh_password)"
}

bosh_username() {
  lpass show --username "$LASTPASS_BOSH_DIRECTOR_CREDENTIALS"
}

bosh_password() {
  lpass show --password "$LASTPASS_BOSH_DIRECTOR_CREDENTIALS"
}

manifest_exists() {
  [ -f deployment ] && [ -f manifest.yml ]
}

delete_deployment() {
  if manifest_exists
  then
    . deployment
    bosh delete deployment "$DEPLOYMENT_NAME" --force
  else
    echo "It doesn't seem that you have created a manifest, you may want to first run script/create-manifest"
  fi
}

delete_manifest() {
  local delete

  read -rp "Do you want to delete the manifest? [yn] " delete
  [[ ! "$delete" =~ [Yy] ]] || rm -f deployment manifest.yml
}

main
