#!/usr/bin/env bash

set -e

SCRIPT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ -n "$1" ]
then
  DEPLOYMENT_CONFIGURATION="$1"
  shift 1
fi

if [ ! -e "$DEPLOYMENT_CONFIGURATION" ]
then
  pushd "$SCRIPT"/../deployment_configurations &> /dev/null
    shopt -s nullglob
    deployment_configurations=( *.yml )
    if [ ${#deployment_configurations[@]} != 0 ]
    then
      echo "Which configuration do you want to deploy?"
      select deployment_configuration in "${deployment_configurations[@]}"
      do
        DEPLOYMENT_CONFIGURATION="$SCRIPT"/../deployment_configurations/"$deployment_configuration"
        break
      done
    else
      echo "There are no deployment configurations, you can create one by running: deploy"
      exit 1
    fi
  popd &> /dev/null
fi

_BOSH_DEPLOYMENT="${DEPLOYMENT_CONFIGURATION/.yml}"
BOSH_DEPLOYMENT="${_BOSH_DEPLOYMENT##*/}"
RMQ_BOSH_RELEASE_MANIFEST="$(yq -r '.bosh_release_manifest' < "$DEPLOYMENT_CONFIGURATION")"
export DEPLOYMENT_CONFIGURATION BOSH_DEPLOYMENT

# shellcheck source=script/_bosh_deploy
. "$SCRIPT"/_bosh_deploy
