#!/usr/bin/env bash

set -e

SCRIPT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# shellcheck source=script/_confirm_bosh_environment
. "$SCRIPT"/_confirm_bosh_environment
# shellcheck source=script/_set_datadog_api_key
. "$SCRIPT"/_set_datadog_api_key
# shellcheck source=script/_set_bosh_deployment
. "$SCRIPT"/_set_bosh_deployment
# shellcheck source=script/_select_rmq_bosh_release
. "$SCRIPT"/_select_rmq_bosh_release
# shellcheck source=script/_select_rmq_server_release
. "$SCRIPT"/_select_rmq_server_release
# shellcheck source=script/_set_rmq_server_package
. "$SCRIPT"/_set_rmq_server_package
# shellcheck source=script/_set_rmq_server_admin_credentials
. "$SCRIPT"/_set_rmq_server_admin_credentials
# shellcheck source=script/_select_erlang_version
. "$SCRIPT"/_select_erlang_version
# shellcheck source=script/_set_erlang_cookie
. "$SCRIPT"/_set_erlang_cookie
# shellcheck source=script/_select_rmq_vm_type
. "$SCRIPT"/_set_rmq_nodes_count
# shellcheck source=script/_select_rmq_network
. "$SCRIPT"/_select_rmq_vm_type
# shellcheck source=script/_select_rmq_persistent_disk_type
. "$SCRIPT"/_select_rmq_persistent_disk_type
# shellcheck source=script/_set_rmq_nodes_count
. "$SCRIPT"/_select_rmq_network
# shellcheck source=script/_select_rmq_az
. "$SCRIPT"/_select_rmq_az
# shellcheck source=script/_select_stemcell
. "$SCRIPT"/_select_stemcell
# shellcheck source=script/_set_cf_apps_domain
. "$SCRIPT"/_set_cf_apps_domain
# shellcheck source=script/_confirm_deployment
. "$SCRIPT"/_confirm_deployment
