#!/usr/bin/env bash

set -e

[ -z "$DEBUG" ] || set -x

LASTPASS_BOSH_DIRECTOR_CREDENTIALS="Shared-London Services/london-ci/bosh-env-tarantino"

BOSH_DIRECTOR_FQDN="tarantino.directors.cf-app.com"

main() {
  ensure_logged_in
  if manifest_exists
  then
    . deployment
    upload_latest_final_release
    bosh deployment manifest.yml
    bosh deploy --no-redact
    ok
  else
    suggest_creating_manifest_first
  fi
}

ensure_logged_in() {
  bosh stemcells &>/dev/null ||
  (
    bosh target "https://$BOSH_DIRECTOR_FQDN:25555"
    bosh login "$(bosh_username)" "$(bosh_password)"
  )
}

bosh_username() {
  lpass show --username "$LASTPASS_BOSH_DIRECTOR_CREDENTIALS"
}

bosh_password() {
  lpass show --password "$LASTPASS_BOSH_DIRECTOR_CREDENTIALS"
}

manifest_exists() {
  [ -f deployment ] && [ -f manifest.yml ]
}

suggest_creating_manifest_first() {
  echo "It doesn't seem that you have created a manifest, you may want to first run script/create-manifest"
  return 1
}

upload_latest_final_release() {
  local final_releases latest_final_release_manifest
  final_releases=(releases/*/*.yml)
  latest_final_release_manifest="${final_releases[*]: -1}"

  bosh upload release "$latest_final_release_manifest"
}

ok() {
  echo "
Successfully deployed $NODES_COUNT node(s) of $RMQ_PACKAGE

  URL:  https://$DEPLOYMENT_NAME.$BOSH_DIRECTOR_FQDN/
  USER: $SERVER_USER
  PASS: $SERVER_PASS

To SSH into any of the RabbitMQ node(s) that you have just deployed:

  cd ../rabbitmq-credentials/bosh
  git pull
  ./ssh
"
}

main
