#!/usr/bin/env bash

set -e

[ -z "$DEBUG" ] || set -x

main() {
  if manifest_exists
  then
    # shellcheck source=/dev/null
    . deployment
  echo "
${RMQ_PACKAGE##*/} deployed on $NODES_COUNT x $NODES_TYPE

  URL:  https://$DEPLOYMENT_NAME.$BOSH_DIRECTOR_FQDN/#/
  USER: $SERVER_USER
  PASS: $SERVER_PASS

To SSH into any of the RabbitMQ node(s):

  cd ../rabbitmq-credentials/bosh
  git pull
  ./ssh
"
    bosh deployment manifest.yml
    bosh instances --ps
  else
    echo "It doesn't seem that you have created a manifest, you may want to first run script/create-manifest"
  fi
}

manifest_exists() {
  [ -f deployment ] && [ -f manifest.yml ]
}

main
